"""empty message

Revision ID: c178de546f6f
Revises: c6d01b77f83d
Create Date: 2026-06-24 09:43:09.720112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c178de546f6f'
down_revision = 'c6d01b77f83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_balance', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('current_balance', sa.Float(), nullable=True))
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=True)
        batch_op.drop_column('current_balance')
        batch_op.drop_column('opening_balance')

    # ### end Alembic commands ###
