"""add_image_file_to_material

Revision ID: d4a7d95a2bf8
Revises: 277c09e1c83c
Create Date: 2026-06-23 17:56:52.265859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4a7d95a2bf8'
down_revision = '277c09e1c83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
