"""empty message

Revision ID: f7f83c87eca4
Revises: c178de546f6f
Create Date: 2026-07-04 16:13:17.598195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f83c87eca4'
down_revision = 'c178de546f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_out', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_expenses', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('other_expenses_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_out', schema=None) as batch_op:
        batch_op.drop_column('discount')
        batch_op.drop_column('other_expenses_details')
        batch_op.drop_column('other_expenses')

    # ### end Alembic commands ###
